sudo: required

# Go for Kubernetes in Docker
language: go
go:
  - '1.11.x'

services:
- docker

before_script:

script:
- set -e                  # Fail fast
- make deploy-kind        # Deploy Kubernetes locally
- make deploy-iofog       # Deploy ioFog services
#- make test              # Test ioFog services
- TAG=rel make push-iofog # Push release packages