apiVersion: apps/v1
kind: Deployment
metadata:
  name: iofog-agent
  labels:
    app: iofog-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iofog-agent
  template:
    metadata:
      labels:
        app: iofog-agent
    spec:
      containers:
      - name: iofog-agent
        image: iofog/agent:dev