apiVersion: apps/v1
kind: Deployment
metadata:
  name: iofog-scheduler
  labels:
    app: iofog-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iofog-scheduler
  template:
    metadata:
      labels:
        app: iofog-scheduler
    spec:
      containers:
      - name: iofog-scheduler
        image: iofog/iofog-scheduler:dev